name: Deploy to GitHub Pages workflow

on:
  push:
    branches:
      - main  # o el nombre de la rama que prefieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAGES_REPO }}
          repository: jvaler01/jvaler01.github.io
          event-type: trigger-workflow