name: Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run github pages workflow
        uses: actions/checkout@v3
        with:
          repository: jvaler01/jvaler01.github.io
          ref: main # Nombre de la rama del repositorio
          workflow_dispatch: deploy.yml # Nombre del flujo de trabajo a ejecutar